# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_require 'dotenv'
default_platform(:ios)

platform :ios do

  before_all do
    Dotenv.overload '.env.secret'
  end

  desc "Runs all tests"
  lane :dev_tests do 
    install_pods()
    scan(
      workspace: ENV["WORK_SPACE"],
      scheme: ENV["CI_SCHEME"],
      devices: ["iPhone 11"],
      code_coverage: true, 
      clean: true,
      slack_url: ENV["SLACK_URL"]
    )
  end

  def install_pods
    cocoapods(
      clean: true,
      podfile: "Podfile",
      try_repo_update_on_error: true
    )
  end
end
