name: Swift

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: release IPA to App Store Connect
    runs-on: macos-latest
    env:
      BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      SLACK_URL: ${{ secrets.SLACK_URL }}
      WORK_SPACE: ${{ secrets.WORK_SPACE }}
      CI_SCHEME: ${{ secrets.CI_SCHEME }}
      

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bundle Install
        run: gem install bundler:1.17.3 && bundle install
      - name: run Unit tests lane
        run: swift test -v
