name: Swift

on:
  push:
    branches: [ Developer ]
  pull_request:
    branches: [ Developer ]

jobs:
  test:
    name: Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bundle Update
        run: gem install bundler:1.17.3
      - name: Bundler Install
        run: bundle install
      - name: run Unit tests lane
        env: 
          SLACK_URL: ${{ secrets.SLACK_URL }}
        run: bundle exec fastlane dev_tests --verbose
